### ISSUE TITLE
ClearTK download too big

### ISSUE THREAD

**Issue by bethard** [ClearTK/cleartk#261]
Original [issue 263](https://code.google.com/p/cleartk/issues/detail?id=263) created by ClearTK on 2011-10-23T22:13:34.000Z:

The latest ClearTK download weighed in at 91MB.  This is because an increasing number of projects are being included with various models.  We need to separate out the downloading of models from the main release which should contain only jar files with .class files and other misc. non-model resources.

**Comment by reckart** [comment]
Big is relative. Today this should no longer matter.
