### ISSUE TITLE
request listing on UIMA site

### ISSUE THREAD

**Issue by bethard** [ClearTK/cleartk#338]
Original [issue 340](https://code.google.com/p/cleartk/issues/detail?id=340) created by ClearTK on 2012-10-26T11:35:12.000Z:

Someone should probably contact the UIMA folks and ask for ClearTK to be listed on their site:

http://uima.apache.org/external-resources.html

They already have uimaFIT, OpenNLP, DKPro, etc. and cTAKES will be there soon.

**Comment by leebecker** [comment]
Looks like ClearTK is now listed on the UIMA external resources list.

**Comment by reckart** [comment]
Maybe you want to provide a slightly more elaborate description through ;) Just post a message to dev@uima
