### ISSUE TITLE
The MutualInformationTest.testMutualInformationFeatureSelection() is failed in Java 1.8.0

### ISSUE THREAD

**Issue by bethard** [ClearTK/cleartk#415]
Original [issue 417](https://code.google.com/p/cleartk/issues/detail?id=417) created by ClearTK on 2015-03-24T17:59:52.000Z:

<b>What steps will reproduce the problem?</b>
Update to the Java version 1.8.0
run MutualInformationTest.testMutualInformationFeatureSelection()

<b>What is the expected output?</b>
Test passes

<b>What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>
ClearTK 2.0.1
java version &quot;1.8.0_40&quot;
OS X Yosemite

Comment:
In the above test, the order of 'Bag_Covered:pig' and 'Bag_Covered:wolf' is changed between two version of java. The information of both cases are the same.

**Comment by leebecker** [comment]
Closing this issue.  Fix uses a TreeBasedTable instead of a HashBasedTable.
