### ISSUE TITLE
ClearTk still on uimafit-core 2.0.0 and uimaj-core 2.5.0, incompatible with current uima

### ISSUE THREAD

**Issue by ThomasGinter** [ClearTK/cleartk#432]
uimaj-core 2.5.0 is incompatible with 2.9.0 which presents an issue with other updated frameworks.

**Comment by ThomasGinter** [comment]
I have forked the repository to work on this issue.

**Comment by reckart** [comment]
Fixed by https://github.com/ClearTK/cleartk/issues/448
