### ISSUE TITLE
Clear TK uses org.apache.opennlp:opennlp-tools:1.5.3 which contains know security issue - should be upgraded to, at-least, 1.8.2 

### ISSUE THREAD

**Issue by joelpeddie** [ClearTK/cleartk#435]
https://www.sourceclear.com/vulnerability-database/vulnerabilities/5215

**Comment by reckart** [comment]
Do you know how to do the upgrade?

See: https://lists.apache.org/thread/r4wj097ombgf18hyyv85p4hlcly56fqc
